import math
promien=int(input('Podaj promien '))
print('Obwod okregu wynosi '+str(((math.pi*(promien*2)))))
print('Pole okregu wynosi '+str((math.pi*promien)**2))
print('Objetosc kuli wynosi '+str((4/3)*(math.pi*promien)**3))
print('Powierzchnia kuli wynosi '+str(4*(math.pi*promien)**2))
bokjedenprostokat=int(input('Podaj pierwszy bok prostokata '))
bokdwaprostokat=int(input('Podaj drugi bok prostokata '))
wysokosc=int(input('Podaj wysokosc prostopadloscianu '))
print('Obwod prostokata wynosi '+str(bokjedenprostokat+bokjedenprostokat+bokdwaprostokat+bokdwaprostokat))
print('Pole prostokata wynosi '+str(bokjedenprostokat*bokdwaprostokat))
print('Objetosc prostopadlosciana wynosi '+str(bokjedenprostokat*bokdwaprostokat*wysokosc))
print('Powierzchnia prostopadlosciana wynosi '+str(2*(bokjedenprostokat*bokdwaprostokat+bokjedenprostokat*wysokosc+bokdwaprostokat*wysokosc)))
wysokoscstozka=int(input('Podaj wysokosc stozka '))
promienstozka=int(input('Podaj promien stozka '))
print('Objetosc stozka wynosi '+str((1/3)*(math.pi*promienstozka)*wysokoscstozka))
